### ISSUE TITLE
False positive exploit?

### ISSUE THREAD

**Issue by sunbeomso** [nescio007/teether#12]
Hi, I have tested teEther on several examples, and I have a question on teEther's analysis result.
It seems that teTher does not consider the amount of Ether to be transferred, which results in false positive exploits.

For example, let's consider the below example code (which can be compiled by solc 0.4.25):
```
contract Test{
  address owner=msg.sender;

  function test(address addr) public {
    addr.transfer(this.balance);
  }
}
```

In this example, the ``test`` function can be invoked by anyone, and consequently, ``.transfer`` can be executed by anyone.
teEther produces an exploit for this contract.

However, this contract cannot have Ethers (i.e., always ``this.balance==0``), because there is no "payable" function. So I think the exploit generated by teEther is false positive.

Could you please point out if I misunderstood something on teEther's results?

**Comment by nescio007** [comment]
Hi,

the example contract you give shows an interesting edge-case of Ethereum: 
The `SELFDESTRUCT` opcode (`0xff`) can be used to transfer funds to another account *without* any checks (or code execution if the target account is another contract, check page 36 of the `4ea7b96`-YellowPaper).
Therefore, even contracts without a payable function *can* have a non-zero balance.

teEther therefore flags this contract as vulnerable, because *all* of its funds can be transferred, and the funds could be non-zero.

**Comment by sunbeomso** [comment]
@nescio007 
Thank you for the answer. Interesting.

Then, does teEther assume that a contract to be analyzed has non-zero Ethers?
In other words, does teEther assume ``address(this).balance > 0``, where ``this`` is the address of the contract to be analyzed?

**Comment by nescio007** [comment]
In a sense, yes :) 

Am 4. August 2020 06:37:12 MESZ schrieb SunBeomSo <notifications@github.com>:

**Comment by sunbeomso** [comment]
@nescio007 Thanks! I close the issue.
