### ISSUE TITLE
How can we know the function invocation details of automatically generated exploits? 

### ISSUE THREAD

**Issue by Andercxt** [nescio007/teether#7]
For example, in the Test contract in Quick Start, I guess the exploit will be first to set up a new transaction by invoking new_transaction(), second to change owner by invoking set_owner() and then lastly to steal the money by invoking approve(). But how can we know these invocation in a randomly given potentially vulnerable contract?

**Comment by nescio007** [comment]
Taking the test contract from the quick start:
The generated exploit it
```
eth.sendTransaction({from:"0x0000000000000000000000000000000000001234", data:"0x7cb97b2b0000000000000000000000000000000000000000000000000000000000001234", to:"0x4000000000000000000000000000000000000000", gasPrice:0})
eth.sendTransaction({from:"0x0000000000000000000000000000000000001234", data:"0x0129ab2700000000000000000000000000000000000000000000000000000000000012340000000000000000000000000000000000000000000000016bc75e2d63100103", to:"0x4000000000000000000000000000000000000000", gasPrice:0})
eth.sendTransaction({from:"0x0000000000000000000000000000000000001234", data:"0xa53a1adfce9e2ef9fe2568f35b22f98bb749862a13e0abd291c6ba4967016d629412829d", to:"0x4000000000000000000000000000000000000000", gasPrice:0})
```

Since the test contract was compiled from Solidity, it follows Solidity's calling convention of 
```
function id (4B) | first argument (32B) | [second argument (32B) ...]
```

The `function id` is computed as the first four bytes of the keccack256 hash over the function *signature*. In the test contract we have

| Function | Signature | ID |
|------|----|-----|
| `approve(bytes32 token)` | `approve(bytes32)` | `a53a1adf` |
| `new_transaction(address to, uint amount)` | `new_transaction(address,uint256)` | `0129ab27` |
| `set_owner(address new_owner)` | `set_owner(address)` | `7cb97b2b` |

Looking at the transaction's data fields we can then decode the first transaction as:
* function: `7cb97b2b` (= `set_owner(address new_owner)`)
* first argument (`new_owner`): `0000000000000000000000000000000000000000000000000000000000001234`

The second transaction as
* function: `0129ab27` (= `new_transaction(address to, uint amount)`)
* first argument (`to`): `0000000000000000000000000000000000000000000000000000000000001234`
* second argument (`amount`): `0000000000000000000000000000000000000000000000016bc75e2d63100103`

And the third transaction as
* function: `a53a1adf` (= `approve(bytes32 token)` )
* first argument (`token`): `ce9e2ef9fe2568f35b22f98bb749862a13e0abd291c6ba4967016d629412829d`

Note however, that this only works as long as you know that the target contract follows Solidity's calling convention and you know the function IDs or signatures.

**Comment by Andercxt** [comment]
Thanks for the quick response. Assuming that the target contract follows the Solidity's calling convention, you say this only works when you know the function IDs or signature, but since this exploit is generated automatically, I guess that your tool also can extract function IDs? If so, where in the code do you do it?

**Comment by nescio007** [comment]
Thanks to the power of symbolic execution, we don't. In fact, teEther is completely agnostic of this calling convention. In the example case it just "learns" that in first transaction the first four bytes *have* to be `7cb97b2b` in order to take the correct path in the control flow graph.

**Comment by Andercxt** [comment]
Oh so you directly get this id from the id checking bytecode in the beginning of the function when executing the symbolic execution, right?

**Comment by nescio007** [comment]
Exactly!

**Comment by Andercxt** [comment]
Thanks a lot!
